---
repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.2.1.1
    hooks:
      - id: buildifier
        args: &args
          - --warnings=all
      - id: buildifier-lint
        args: *args
