# Cut a release whenever a new tag is pushed to the repo.
---
name: Release

on:  # yamllint disable rule:truthy
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create release archive and notes
        run: .github/workflows/create_archive_and_notes.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # Use GH feature to populate the changelog automatically
          generate_release_notes: true
          body_path: release_notes.txt
          fail_on_unmatched_files: true
          files: rules_shellcheck-*.tar.gz
