name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test fetch
        run: bazel fetch //...

      - name: Test
        run: bazel test //...

  test-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: bazel test //...
